### ISSUE TITLE
Hide Types Behind ABI3 Features

### ISSUE THREAD

**Issue by erichulburd** [rigetti/rigetti-pyo3#36]
When building with a PyO3 `abi3-py38` feature, I've received the following error:

```
error[E0432]: unresolved imports `pyo3::types::PyDate`, `pyo3::types::PyDateTime`, `pyo3::types::PyDelta`, `pyo3::types::PyTime`, `pyo3::types::PyTzInfo`
  --> ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rigetti-pyo3-0.3.1/src/to_python.rs:27:13
   |
27 |     types::{PyDate, PyDateTime, PyDelta, PyTime, PyTzInfo},
   |             ^^^^^^  ^^^^^^^^^^  ^^^^^^^  ^^^^^^  ^^^^^^^^ no `PyTzInfo` in `types`
   |             |       |           |        |
   |             |       |           |        no `PyTime` in `types`
   |             |       |           |        help: a similar name exists in the module: `PyType`
   |             |       |           no `PyDelta` in `types`
   |             |       no `PyDateTime` in `types`
   |             no `PyDate` in `types`
```

This means no crate building with `abi3-py38` can build if it depends on `rigetti-pyo3`. As such, these imports and functionality that depends on them should be hidden behind an appropriate `abi3-py*` feature (or lack thereof).

To test this in CI, try building a simple module extension with and without the appropriate `abi3-py*` features that do not use the `PyDate`, et al. objects; the build should not fail with an error similar to that above.

**Comment by antalsz** [comment]
PRs #45 and #46 fix this, but I think it would be great to get some sort of test for this – I somehow had to do two PRs because I missed one set of files along the way.

**Comment by antalsz** [comment]
#46 closes this and includes better testing on builds.
